//this function generated by ChatGPT
function updateImageSize(image, referenceText) {
  // hidden element to measure title height
  const measureSpan = document.createElement('span');
  measureSpan.className = 'measure-span';
  measureSpan.style.font = window.getComputedStyle(referenceText).font;
  measureSpan.textContent = 'Hg';
  document.body.appendChild(measureSpan);

  const textHeight = measureSpan.offsetHeight;
  document.body.removeChild(measureSpan);

  const aspectRatio = image.naturalWidth / image.naturalHeight;
  image.style.height = `${textHeight}px`;
  image.style.width = `${textHeight * aspectRatio}px`;
}

function observeTextResize(imageId, referenceTextSelector) {
  const referenceText = document.querySelector(referenceTextSelector);
  const image = document.getElementById(imageId);

  const resizeObserver = new ResizeObserver(() => {
    updateImageSize(image, referenceText);
  });

  resizeObserver.observe(referenceText);
  updateImageSize(image, referenceText); //initial call
}

window.onload = () => {
  observeTextResize('imageToResize', '#textContainer');
};

//Toggleable menu for mobile
function displayDropdown() {
  var drop = document.getElementById("dropdown");
  if (drop.style.display === "block") {
    drop.style.display = "none";
  } else {
    drop.style.display = "block"
  }
}

document.getElementById("hamburgerIcon").addEventListener("click", displayDropdown);

function expandTable() {
  var table = document.getElementById("contentTable");
  if (table.style.display === "block") {
    table.style.display = "none";
  } else {
    table.style.display = "block";
  }
}
document.getElementById("contentIcon").addEventListener("click", expandTable);